### ISSUE TITLE
iot cloud install error

### ISSUE THREAD

**Issue by microfoundry** [awslabs/simpleiot-cli#11]
I attempted to run through the "iot cloud install" process and always ended up with the same failure message:

Iotcdk: creating CloudFormation changeset...
1:31:22 AM | CREATE_FAILED        | AWS::CloudFormation::Stack | s3NestedStacks3Nes...ckResource4EAEB761
Embedded stack arn:aws:cloudformation:eu-central-1:417160830473:stack/Iotcdk-s3NestedStacks3NestedStackResource4EAEB761-1ELTKXCH9QTLV/907d6930-1f8a-11ee-8173-02aa7e4719f4 was
not successfully created: The following resource(s) failed to create: [s3generatorbucket374CC269, s3templatebucket9F64E024, s3twinmediabucket21FC0B3C, s3dashboardbucket988996B
F, s3fwupdatebucket874CB9FE].

 ❌  Iotcdk failed: Error: The stack named Iotcdk failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Embedded stack arn:aws:cloudformation:eu-central-1:417160830473:stack/Iotcdk-s3NestedStacks3NestedStackResource4EAEB761-1ELTKXCH9QTLV/907d6930-1f8a-11ee-8173-02aa7e4719f4 was not successfully created: The following resource(s) failed to create: [s3generatorbucket374CC269, s3templatebucket9F64E024, s3twinmediabucket21FC0B3C, s3dashboardbucket988996BF, s3fwupdatebucket874CB9FE].
    at FullCloudFormationDeployment.monitorDeployment (/usr/lib/node_modules/aws-cdk/lib/index.js:327:10235)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async deployStack2 (/usr/lib/node_modules/aws-cdk/lib/index.js:330:144733)
    at async /usr/lib/node_modules/aws-cdk/lib/index.js:330:130251
    at async run (/usr/lib/node_modules/aws-cdk/lib/index.js:330:128257)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named Iotcdk failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Embedded stack arn:aws:cloudformation:eu-central-1:417160830473:stack/Iotcdk-s3NestedStacks3NestedStackResource4EAEB761-1ELTKXCH9QTLV/907d6930-1f8a-11ee-8173-02aa7e4719f4 was not successfully created: The following resource(s) failed to create: [s3generatorbucket374CC269, s3templatebucket9F64E024, s3twinmediabucket21FC0B3C, s3dashboardbucket988996BF, s3fwupdatebucket874CB9FE].
    at deployStacks (/usr/lib/node_modules/aws-cdk/lib/index.js:330:130558)
    at async CdkToolkit.deploy (/usr/lib/node_modules/aws-cdk/lib/index.js:330:146782)
    at async exec4 (/usr/lib/node_modules/aws-cdk/lib/index.js:385:51296)
****************************************************
*** Newer version of CDK is available [2.87.0]   ***
*** Upgrade recommended (npm install -g aws-cdk) ***
****************************************************

Stack Deployments Failed: Error: The stack named Iotcdk failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Embedded stack arn:aws:cloudformation:eu-central-1:417160830473:stack/Iotcdk-s3NestedStacks3NestedStackResource4EAEB761-1ELTKXCH9QTLV/907d6930-1f8a-11ee-8173-02aa7e4719f4 was not successfully created: The following resource(s) failed to create: [s3generatorbucket374CC269, s3templatebucket9F64E024, s3twinmediabucket21FC0B3C, s3dashboardbucket988996BF, s3fwupdatebucket874CB9FE].

**Comment by microfoundry** [comment]
I spotted this in the CloudFormation: Iotcdk-s3NestedStacks3NestedStackResource4EAEB761-1ELTKXCH9QTLV: Events:

Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: BMM23XRGS1XPC9P2; S3 Extended Request ID: SUpTp9XaFL/F3WpV8nFOl6v6fwdVKyYkdqAmn4ROsbpVMIZwUrr+fbc5wXJKkKMni4x8X+b6hd4=; Proxy: null)

**Comment by lukaszaj** [comment]
I've got a similar issue, backend deployment always trips up on those S3 buckets. I see two problems here, first of all the bucket names won't be unique (assuming anyone deployed this successfully, unless they get cleaned up later in the process) and also bucket names can't contain upper case characters.
The bootstrap stage completes without problems, this error comes up during Team deployment. 
 Any ideas on how to fix it would be great :)
